### Auth Register
POST {{BASE_URL}}/register
Content-Type: application/json

{
  "email": "ukoji1elvis@gmail.com",
  "password": "0243649608",
  "firstName": "Elvis",
  "lastName": "Solomon"
}
###

### Auth login
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "ukojielvis@gmail.com",
  "password": "0243649608"
}
###