### Auth Register
POST {{BASE_URL}}/register
Content-Type: application/json

{
  "email": "kfrimpong1@gmail.com",
  "password": "0243649608",
  "firstName": "Kwaku",
  "lastName": "Frimpong"
}
###

### Auth login
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "ukojielvis@gmail.com",
  "password": "0243649608"
}
###