@BASE_URL = https://redeemfund-api.herokuapp.com/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDM4YTgwN2Q4MTFkZWY5NjEwYTNmMSIsImlhdCI6MTYzMTgxNjMyMH0.5dCEC5StIOTno3Ys-RiK8iwVEc3f-HYHcrH7IM8ilNo

GET {{BASE_URL}}/beneficiary/6146de0ad20a8578b062be86
Authorization: Bearer {{accessToken}}
###Get Beneficary by Id

PATCH {{BASE_URL}}/beneficiary
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "countryCode": "GH",
  "countryName": "Ghana",
  "profilePhotoS3": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Justin_Bieber_in_Rosemont%2C_Illinois_%282015%29.jpg/440px-Justin_Bieber_in_Rosemont%2C_Illinois_%282015%29.jpg",
  "phoneNumber": "+233552587984"

}

