POST {{BASE_URL}}/make-payment/react-js-crash-course-on-skill-share
Content-Type: application/json

{
  "phoneNumber" : "0552587984",
  "fullName": "Elvis Ukoji Solomon",
  "email": "k98@gmail.com",
  "amount": 40
}
###Test payment link



GET {{BASE_URL}}/campaign/react-js-crash-course-on-skill-share
###Get campaign by slug

@BASE_URL = https://redeemfund-api.herokuapp.com/api
@accessTokens = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDM4YTgwN2Q4MTFkZWY5NjEwYTNmMSIsImlhdCI6MTYzMTgxNjMyMH0.5dCEC5StIOTno3Ys-RiK8iwVEc3f-HYHcrH7IM8ilNo


GET {{BASE_URL}}/campaigns
###Get all campaigns

### post campaign
POST {{BASE_URL}}/campaigns
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Lorep Ipsum test three",
  "goalAmount": 2000,
  "description": "Testing mic 123",
  "fundType": "FLEXIBLE_FUND",
  "coverPictureS3": "https://4.img-dpreview.com/files/p/E~TC4x3S1180x0~articles/8388257571/Image_Canon_II.jpeg",
  "platform": "AIRTIME"

}
###

